name: Docker Image CI

on:
  push:
    branches: [develop, main, master]
  pull_request:
    branches: [develop, main, master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag scrum_simulator:$(date +%s)

# TODO --- Writing Test cases for SCRUM - Simulator
# Write steps here to execute test cases and put commands for test execution
